
skillMetadata:
  sections:
    - name: Sonos Node Server IP Address
      fields:
        - name: explanation_label_01
          type: label
          label: Enter here the (local) IP Address or Hostname of your Sonos Node JS HTTP Server
        - name: sonos_server_ip
          type: text
          label: IP Address or Hostname
          value: ""
    - name: Room
      fields:
        - type: label
          name: explanation_label_02
          label: Enter here the exact name of the room (the one displayed in the Sonos app) your Mycroft AI Speaker is located in. Type it in with spaces but please watch out with non standard characters like ä, é or ø. Those can be a bit tricky
        - name: room
          type: text
          label: Room
          value: ""
    - name: Radio
      fields:
        - type: label
          name: explanation_label_03
          label: To play radio on Sonos, add a radio sender to your Sonos favorites and rename it to something Mycroft can understand. Then enter here the name of the just created favorite
        - name: radio
          type: text
          label: Radio
          value: ""
    

