
skillMetadata:
  sections:
    - name: Services
      fields:
        - name: service_selection
          type: select
          label: Select your music service
          options: Spotify (NOT WORKING)|spotify;Apple Music|apple_music
          value: spotify

    - name: Radio
      fields:
        - type: label
          label: To play radio on Sonos, add a radio sender to your Sonos favorites and rename it to something Mycroft can understand. Then enter here the name of the just created favorite
        - name: radio
          type: text
          label: Radio
          value: ""
    

