skillMetadata:
  sections:
    - name: Services
      fields:
        - name: service_selection
          type: select
          label: Select your music service
          options: Spotify|spotify;Apple Music|apple_music
          value: apple_music 