
skillMetadata:
  sections:
    - name: Sonos Node Server IP Address
      fields:
        - name: sonos_node_server_ip_explanation_label
          type: label
          label: Enter here the (local) IP Address or Hostname of your Sonos Node JS HTTP Server
        - name: sonos_server_ip
          type: text
          label: IP Address or Hostname
          value: ""
    - name: Radio
      fields:
        - type: label
          name: explanation_label_03
          label: To play radio on Sonos, add a radio sender to your Sonos favorites and rename it to something Mycroft can understand. Then enter here the name of the just created favorite
        - name: radio
          type: text
          label: Radio
          value: ""
    

